# -*- coding: utf-8 -*-
"""casting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKZY2JuvGLEdVlX5CZdRHOKQJ_sZBj6k

casting
konversi tipe data otomatis
"""

nama = "lendis fabri"
usia = '20'
lajang = True
print(type(nama))
print(type(usia))
print(type(lajang))

"""konversi tipe data"""

usia = input('usia anda:')
print(type(usia))

panjang = input('masukan panjang')

a = 10/2
print(type(a))
b = 6/2
print(type(b))

jeruk = "jeruk"
kata = jeruk*5
print(type(kata))

panjang = input('masukan panjang:')
lebar = input('masukan lebar:')
print('luas=', float(panjang) * float(lebar))

panjang = int(input('masukan panjang'))
lebar = int(input('masukan lebar'))
print('luas=', panjang * lebar)

nama = 'jaya'
tahun_lahir = 1988
print(nama+' lahir ditahun '+str(tahun_lahir))