# -*- coding: utf-8 -*-
"""manipulation string and escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_b8Nq8vqokqrXGRBo9vt96gFYheVeY3X
"""

asal_kota = "Bandar lampung"
kode_pos = "35144"
asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

"""
string"""

nama ="darma"
asal ="indonsia"
print(nama)
print(asal)

"""manipulasi string"""

print(nama,asal)

print(nama+asal)

print("halo nama saya",nama)

"""escpe characters"""

print('dia berkata:"pergilah"')

print("aku menimpali : \"apakah kau ingin aku'angkat kaki'?\"")

print("\\(^_^)/(\\*~*/)")