# -*- coding: utf-8 -*-
"""manipulasi string 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOHhZ1Cky37L6oFdT8MI-ahrg8df9AI8

format string pada python
"""

template = "halo saya %s dari %s"
print(template %('Felix Darma','Indonesia'))

"""fungsi format"""

template = 'halo saya {Felix} dari {punggur}'
template_2 = 'saya suka makan {} dan minum{}'

print(template.format(Felix='Felix Darma', punggur='Indonesia'))
print(template_2.format('bakso', 'es jeruk'))

"""string interpolation"""

nama = 'felix'
asal = 'punggur'
print(f'perkenalkan saya {nama} dari{asal}')

alamat= 'surabaya,''punggur,''jawatengah,'
print(alamat.split())

alamat= 'surabaya,''punggur,''jawatengah,'
print(alamat.split(','))

alamat= 'surabaya,''punggur,''jawatengah,'
print(alamat.split(', '))

"""string menjadi list dan sebalik nya"""

print('🗿'.join(['aku','suka','python']))

print('🗿'.join(alamat.split(',')))

print('halo selamat pagi'.upper())
print('halo selamat siang'.upper())

print('AZIZUN HAKIM'.lower())
print('MAIN FREE FIRE'.lower())

print('kemanapun arah mata angin membawaku pergi'.title())
print('GAME OF THRONE'.title())

print('kemanapun arah mata angin membawaku pergi'.swapcase())
print('GAME OF THRONE'.swapcase())

"""mencari sebuah kata"""

angka = '12345'
print('index angka 3:',angka.find('3'))
print('index angka 45:',angka.find('45'))
print('index angka 12:',angka.find('12'))
print('index angka 35:',angka.find('35'))

"""mereplace"""

ibu_kota = 'Nyawit'
print(ibu_kota.replace('a','i'))
print(ibu_kota.replace('yaw','🗿'))

print(ibu_kota.replace('a',''))

paragraf='saya menemukan bola naga ke-tujuh di atlanta'
x= paragraf.count('di')
print(f'kata"di"muncul sebanyaqk {x} kali')