# -*- coding: utf-8 -*-
"""module and packages

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxiY-fHBZW62hNQubQocriHww1tPnxLx

#Nama : Felix Darmaja
#NPM : 2411012035
#modul dan paket

modular adalah proses pemecah progam dari besar menjadi bagian kecil yang terpisah,bagian bagian ini terorganisir dan terkelola rapi sesuai tugas nya
keunggulan
simplicity
maintibility
reusability
tiga komponen dalam modular ada fungsi,modul,paket
modul adalah sebuah file bereksistensi .py yg berisi skrip python
modul bisa berisi fungsi,variabel,maupun class
"""

import matematika
print(matematika.pi)

print("nilai PI:", matematika.pi)
print("luas lingkaran (r=21):", matematika.luas_lingkaran(radius=21))
print("luas persegi (s=12):", matematika.luas_persegi(sisi=12))

from matematika import luas_persegi as lp
from matematika import luas_lingkaran as ll

print("luas persegi (s=10):", lp(10))
print("luas lingkaran (r=7):", ll(7))

from luas.segitiga import luas_segitiga

print("luas segitiga(alas=10, tinggi=5):", luas_segitiga(10, 5))

import math
import datetime

waktu_sekarang = datetime.datetime.now()
print("tanggal dan waktu saat ini:", waktu_sekarang)

print("nilai pi dari modul math:", math.pi)