# -*- coding: utf-8 -*-
"""Tugas Kelompok Compro 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ELnU2qZ6MIgMwMPwyndn0-3xs6w8ofm
"""

# TUGAS 1 - COMPUTER PROGRAMMING 2
# String Manipulation & Data Cleaning

# 1.DATA INPUT
data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "
print(f"Data Mentah: '{data_kotor}'\n")

# 2.Proses pembersihan

# 2a.Menghapus spasi untuk ujung karakter diawal
data_bersih=data_kotor.strip()
data_bersih=data_bersih.replace("#","")

# 2b.memecah string menjadi list berdasarkan tanda pemisah '-'
data_list=data_bersih.split("-")

# 2c.mengelola daftar skill
skill_list=data_list[3].split(",")
skill_dikuasai=" & ".join(skill_list)

# 2d.menghitung panjang ID dan jumlah skill
id_pendaftar=data_list[0]
panjang_id=len(id_pendaftar)
total_skill=len(skill_list)

# 3.output akhir
print('=' * 40)
print("     HASIL VERIFIKASI DATA")
print('=' * 40)

# menggunakan ljust() agar titik dua sejajar
print(f"{'ID Pendaftar':15} : {id_pendaftar}({panjang_id}digit)")
print(f"{'Nama Lengkap':15} : {data_list[1].title()}")
print(f"{'Progam Studi':15} : {data_list[2].upper()}")
print(f"{'Skill Dikuasai':15} : {skill_dikuasai}")
print(f"{'Total Skill':15} : {total_skill}")
print(f"{'Status Akun':15} : {data_list[4].capitalize()}")

print('=' * 40)

"""PENJELASAN
Bagian awal terdapat print(f") atau bisa disebut f-string disitu (f) bekerja sebagai shortcut data agar lebih ringkas dan terlihat profesional jika tidak memakai (f) kita bisa menggunakan (+) tapi ini membuat lebih panjang

.strip berfungsi sebagai penghapus spasi yg tidak diperlukan entah itu di ujung awal atau akhir

.replace berfungsi untuk mengganti sebuah data yg ada kasus di atas yg diganti yaitu id #001 nah pagar didepan angka ingin dihilangkan atau dikosongkan maka dari itu penulisan kode menjadi
.replace("#" "") untuk mengganti atau menghilangkan tanda (#) maka hasil yg didapat id 001

untuk data_list[3].split maksudnya disini ada angka tiga nah angka tiga ini sebagai koordinat yg tepat untuk data skill karena dalam dunia pemrogaman hitungan dimulai dari angka 0 nah untuk .split nya sendiri bertugas untuk memecah satu kalimat panjang (string)

.join ini kebalikan dari split nah jika split untuk memecah kalimat nah .join ini berfungsi sebagai penyatu kalimat

len nah untuk len ini berfungsi sebagai pengukur dalam sebuah data atau untuk menghitung jumlah dalam data dalam kasus ini disini len menghitung id dan total skill id sendiri berjumlah 3 digit dan total skill juga 3

nah untuk print("=" * 40) ini untuk batas yg seperti diatas = itu objek nya dan *40 ini dimaksudkan untuk jumlah = yg dikeluarkan
"""